_welcome:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

_demo_secured:
    resource: "@AcmeDemo/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemo/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo
