parameters:
    module_register.class:    AirOS\ControlCenterBundle\Service\ModuleRegister

services:
    module_register:
        class:        %module_register.class%
        arguments:    [@session]